### ISSUE TITLE
Character encoding error (unicode to UTF-8)

### ISSUE THREAD

**Issue by SamAmann** [AntoinePaix/scraping-classement-atout-france#1]
Traceback (most recent call last):
  File "c:\Users\***\repos\scraping-classement-atout-france\atout_france.py", line 169, in <module>
    client.download_all_datas()
  File "c:\Users\***\repos\scraping-classement-atout-france\atout_france.py", line 162, in download_all_datas
    csv_file.writerow(hotel)
  File "C:\Python311\Lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 68: character maps to <undefined>

This error occurs when the script tries to write a character that is not supported by the encoding used by the CSV writer. 
Specifically, the character '\u0301' (which represents an acute accent) cannot be encoded using the 'cp1252' encoding. 

To fix this error, you can try changing the encoding used by the CSV writer to 'utf-8', then add a function to modify
each special character on writing.

I'll try a proposition to PR.

**Comment by AntoinePaix** [comment]
@SamAmann I will fix the scraper tonight, thanks for the issue.

**Comment by AntoinePaix** [comment]
fixed 30da21939446554d203370d5d45891d8f348f870
